const mongoose = require('mongoose'),
        moment = require('moment');

const evaluacionAspectosAmbientalesSchema = new mongoose.Schema({

        F1:{
          type:Number,
          required: true,
          default:false
        },
        N1:{
          type:Number,
          required: true,
          default:false
        },
        M1:{
          type:Number,
          required: true,
          default:false
        },
        F2:{
          type:Number,
          required: true,
          default:false
        },
        N2:{
          type:Number,
          required: true,
          default:false
        },
        M2:{
          type:Number,
          required: true,
          default:false
        },
        F3:{
          type:Number,
          required: true,
          default:false
        },
        N3:{
          type:Number,
          required: true,
          default:false
        },
        M3:{
          type:Number,
          required: true,
          default:false
        },
        F4:{
          type:Number,
          required: true,
          default:false
        },
        N4:{
          type:Number,
          required: true,
          default:false
        },
        M4:{
          type:Number,
          required: true,
          default:false
        },
        F5:{
          type:Number,
          required: true,
          default:false
        },
        N5:{
          type:Number,
          required: true,
          default:false
        },
        M5:{
          type:Number,
          required: true,
          default:false
        },
        F6:{
          type:Number,
          required: true,
          default:false
        },
        N6:{
          type:Number,
          required: true,
          default:false
        },
        M6:{
          type:Number,
          required: true,
          default:false
        },
        F7:{
          type:Number,
          required: true,
          default:false
        },
        N7:{
          type:Number,
          required: true,
          default:false
        },
        M7:{
          type:Number,
          required: true,
          default:false
        },
        F8:{
          type:Number,
          required: true,
          default:false
        },
        N8:{
          type:Number,
          required: true,
          default:false
        },
        M8:{
          type:Number,
          required: true,
          default:false
        },
        F9:{
          type:Number,
          required: true,
          default:false
        },
        N9:{
          type:Number,
          required: true,
          default:false
        },
        M9:{
          type:Number,
          required: true,
          default:false
        },
        F10:{
          type:Number,
          required:true,
          default:false 
        },
        N10:{
          type:Number,
          required:true,
          default:false 
        },
        M10:{
          type:Number,
          required:true,
          default:false 
        },
        F11:{
          type:Number,
          required:true,
          default:false 
        },
        N11:{
          type:Number,
          required:true,
          default:false 
        },
        M11:{
          type:Number,
          required:true,
          default:false 
        },
        F12:{
          type:Number,
          required:true,
          default:false 
        },
        N12:{
          type:Number,
          required:true,
          default:false 
        },
        M12:{
          type:Number,
          required:true,
          default:false 
        },
        F13:{
          type:Number,
          required:true,
          default:false 
        },
        N13:{
          type:Number,
          required:true,
          default:false 
        },
        M13:{
          type:Number,
          required:true,
          default:false 
        },
        F14:{
          type:Number,
          required:true,
          default:false 
        },
        N14:{
          type:Number,
          required:true,
          default:false 
        },
        M14:{
          type:Number,
          required:true,
          default:false 
        },
        F15:{
          type:Number,
          required:true,
          default:false 
        },
        N15:{
          type:Number,
          required:true,
          default:false 
        },
        M15:{
          type:Number,
          required:true,
          default:false 
        },
        F16:{
          type:Number,
          required:true,
          default:false 
        },
        N16:{
          type:Number,
          required:true,
          default:false 
        },
        M16:{
          type:Number,
          required:true,
          default:false 
        },
        F17:{
          type:Number,
          required:true,
          default:false 
        },
        N17:{
          type:Number,
          required:true,
          default:false 
        },
        M17:{
          type:Number,
          required:true,
          default:false 
        },
        F18:{
          type:Number,
          required:true,
          default:false 
        },
        N18:{
          type:Number,
          required:true,
          default:false 
        },
        M18:{
          type:Number,
          required:true,
          default:false 
        },
        F19:{
          type:Number,
          required:true,
          default:false 
        },
        N19:{
          type:Number,
          required:true,
          default:false 
        },
        M19:{
          type:Number,
          required:true,
          default:false 
        },
        F20:{
          type:Number,
          required:true,
          default:false 
        },
        N20:{
          type:Number,
          required:true,
          default:false 
        },
        M20:{
          type:Number,
          required:true,
          default:false 
        },
        F21:{
          type:Number,
          required:true,
          default:false 
        },
        N21:{
          type:Number,
          required:true,
          default:false 
        },
        M21:{
          type:Number,
          required:true,
          default:false 
        },
        F22:{
          type:Number,
          required:true,
          default:false 
        },
        N22:{
          type:Number,
          required:true,
          default:false 
        },
        M22:{
          type:Number,
          required:true,
          default:false 
        },
        F23:{
          type:Number,
          required:true,
          default:false 
        },
        N23:{
          type:Number,
          required:true,
          default:false 
        },
        M23:{
          type:Number,
          required:true,
          default:false 
        },
        F24:{
          type:Number,
          required:true,
          default:false 
        },
        N24:{
          type:Number,
          required:true,
          default:false 
        },
        M24:{
          type:Number,
          required:true,
          default:false 
        },
        F25:{
          type:Number,
          required:true,
          default:false 
        },
        N25:{
          type:Number,
          required:true,
          default:false 
        },
        M25:{
          type:Number,
          required:true,
          default:false 
        },
        F26:{
          type:Number,
          required:true,
          default:false 
        },
        N26:{
          type:Number,
          required:true,
          default:false 
        },
        M26:{
          type:Number,
          required:true,
          default:false 
        },
        F27:{
          type:Number,
          required:true,
          default:false 
        },
        N27:{
          type:Number,
          required:true,
          default:false 
        },
        M27:{
          type:Number,
          required:true,
          default:false 
        },
        F28:{
          type:Number,
          required:true,
          default:false 
        },
        N28:{
          type:Number,
          required:true,
          default:false 
        },
        M28:{
          type:Number,
          required:true,
          default:false 
        },
        F29:{
          type:Number,
          required:true,
          default:false 
        },
        N29:{
          type:Number,
          required:true,
          default:false 
        },
        M29:{
          type:Number,
          required:true,
          default:false 
        },
        F30:{
          type:Number,
          required:true,
          default:false 
        },
        N30:{
          type:Number,
          required:true,
          default:false 
        },
        M30:{
          type:Number,
          required:true,
          default:false 
        },
        F31:{
          type:Number,
          required:true,
          default:false 
        },
        N31:{
          type:Number,
          required:true,
          default:false 
        },
        M31:{
          type:Number,
          required:true,
          default:false 
        },
        F32:{
          type:Number,
          required:true,
          default:false 
        },
        N32:{
          type:Number,
          required:true,
          default:false 
        },
        M32:{
          type:Number,
          required:true,
          default:false 
        },
        F33:{
          type:Number,
          required:true,
          default:false 
        },
        N33:{
          type:Number,
          required:true,
          default:false 
        },
        M33:{
          type:Number,
          required:true,
          default:false 
        },
        F34:{
          type:Number,
          required:true,
          default:false 
        },
        N34:{
          type:Number,
          required:true,
          default:false 
        },
        M34:{
          type:Number,
          required:true,
          default:false 
        },
        F35:{
          type:Number,
          required:true,
          default:false 
        },
        N35:{
          type:Number,
          required:true,
          default:false 
        },
        M35:{
          type:Number,
          required:true,
          default:false 
        },
        F36:{
          type:Number,
          required:true,
          default:false 
        },
        N36:{
          type:Number,
          required:true,
          default:false 
        },
        M36:{
          type:Number,
          required:true,
          default:false 
        },
        F37:{
          type:Number,
          required:true,
          default:false 
        },
        N37:{
          type:Number,
          required:true,
          default:false 
        },
        M37:{
          type:Number,
          required:true,
          default:false 
        },
        F38:{
          type:Number,
          required:true,
          default:false 
        },
        N38:{
          type:Number,
          required:true,
          default:false 
        },
        M38:{
          type:Number,
          required:true,
          default:false 
        },
})

module.exports = mongoose.model("Evaluacion Aspectos Ambientales",evaluacionAspectosAmbientalesSchema)
