const mongoose = require('mongoose'),
      moment = require('moment');

const puntoDosListadoPeligrosSchema = new mongoose.Schema({
    
    C1P1:{
     type:String,
     required:true,
     default:false
    },
    C1P2:{
     type:String,
     required:true,
     default:false
    },
    C1P3:{
     type:String,
     required:true,
     default:false
    },
    C1P4:{
     type:String,
     required:true,
     default:false
    },
    C2P1:{
     type:String,
     required:true,
     default:false
    },
    C2P2:{
     type:String,
     required:true,
     default:false
    },
    C2P3:{
     type:String,
     required:true,
     default:false
    },
    C2P4:{
     type:String,
     required:true,
     default:false
    },
    C3P1:{
     type:String,
     required:true,
     default:false
    },
    C3P2:{
     type:String,
     required:true,
     default:false
    },
    C3P3:{
     type:String,
     required:true,
     default:false
    },
    C3P4:{
     type:String,
     required:true,
     default:false
    },
    C4P1:{
     type:String,
     required:true,
     default:false
    },
    C4P2:{
     type:String,
     required:true,
     default:false
    },
    C4P3:{
     type:String,
     required:true,
     default:false
    },
    C4P4:{
     type:String,
     required:true,
     default:false
    },
    C5P1:{
     type:String,
     required:true,
     default:false
    },
    C5P2:{
     type:String,
     required:true,
     default:false
    },
    C5P3:{
     type:String,
     required:true,
     default:false
    },
    C5P4:{
     type:String,
     required:true,
     default:false
    },
    C6P1:{
     type:String,
     required:true,
     default:false
    },
    C6P2:{
     type:String,
     required:true,
     default:false
    },
    C6P3:{
     type:String,
     required:true,
     default:false
    },
    C6P4:{
     type:String,
     required:true,
     default:false
    },
    C7P1:{
     type:String,
     required:true,
     default:false
    },
    C7P2:{
     type:String,
     required:true,
     default:false
    },
    C7P3:{
     type:String,
     required:true,
     default:false
    },
    C7P4:{
     type:String,
     required:true,
     default:false
    },
    C8P1:{
     type:String,
     required:true,
     default:false
    },
    C8P2:{
     type:String,
     required:true,
     default:false
    },
    C8P3:{
     type:String,
     required:true,
     default:false
    },
    C8P4:{
     type:String,
     required:true,
     default:false
    },
    C9P1:{
     type:String,
     required:true,
     default:false
    },
    C9P2:{
     type:String,
     required:true,
     default:false
    },
    C9P3:{
     type:String,
     required:true,
     default:false
    },
    C9P4:{
     type:String,
     required:true,
     default:false
    },
    C10P1:{
     type:String,
     required:true,
     default:false   
    },
    C10P2:{
     type:String,
     required:true,
     default:false   
    },
    C10P3:{
     type:String,
     required:true,
     default:false   
    },
    C10P4:{
     type:String,
     required:true,
     default:false   
    },
    C11P1:{
     type:String,
     required:true,
     default:false   
    },
    C11P2:{
     type:String,
     required:true,
     default:false   
    },
    C11P3:{
     type:String,
     required:true,
     default:false   
    },
    C11P4:{
     type:String,
     required:true,
     default:false   
    },
    C12P1:{
     type:String,
     required:true,
     default:false   
    },
    C12P2:{
     type:String,
     required:true,
     default:false   
    },
    C12P3:{
     type:String,
     required:true,
     default:false   
    },
    C12P4:{
     type:String,
     required:true,
     default:false   
    },
    C13P1:{
     type:String,
     required:true,
     default:false   
    },
    C13P2:{
     type:String,
     required:true,
     default:false   
    },
    C13P3:{
     type:String,
     required:true,
     default:false   
    },
    C13P4:{
     type:String,
     required:true,
     default:false   
    },
    C14P1:{
     type:String,
     required:true,
     default:false   
    },
    C14P2:{
     type:String,
     required:true,
     default:false   
    },
    C14P3:{
     type:String,
     required:true,
     default:false   
    },
    C14P4:{
     type:String,
     required:true,
     default:false   
    },
    C15P1:{
     type:String,
     required:true,
     default:false   
    },
    C15P2:{
     type:String,
     required:true,
     default:false   
    },
    C15P3:{
     type:String,
     required:true,
     default:false   
    },
    C15P4:{
     type:String,
     required:true,
     default:false   
    },
    C16P1:{
     type:String,
     required:true,
     default:false   
    },
    C16P2:{
     type:String,
     required:true,
     default:false   
    },
    C16P3:{
     type:String,
     required:true,
     default:false   
    },
    C16P4:{
     type:String,
     required:true,
     default:false   
    },
    C17P1:{
     type:String,
     required:true,
     default:false   
    },
    C17P2:{
     type:String,
     required:true,
     default:false   
    },
    C17P3:{
     type:String,
     required:true,
     default:false   
    },
    C17P4:{
     type:String,
     required:true,
     default:false   
    },
    C18P1:{
     type:String,
     required:true,
     default:false   
    },
    C18P2:{
     type:String,
     required:true,
     default:false   
    },
    C18P3:{
     type:String,
     required:true,
     default:false   
    },
    C18P4:{
     type:String,
     required:true,
     default:false   
    },
    C19P1:{
     type:String,
     required:true,
     default:false   
    },
    C19P2:{
     type:String,
     required:true,
     default:false   
    },
    C19P3:{
     type:String,
     required:true,
     default:false   
    },
    C19P4:{
     type:String,
     required:true,
     default:false   
    },
    C20P1:{
     type:String,
     required:true,
     default:false   
    },
    C20P2:{
     type:String,
     required:true,
     default:false   
    },
    C20P3:{
     type:String,
     required:true,
     default:false   
    },
    C20P4:{
     type:String,
     required:true,
     default:false   
    },
    C21P1:{
     type:String,
     required:true,
     default:false   
    },
    C21P2:{
     type:String,
     required:true,
     default:false   
    },
    C21P3:{
     type:String,
     required:true,
     default:false   
    },
    C21P4:{
     type:String,
     required:true,
     default:false   
    },
    C22P1:{
     type:String,
     required:true,
     default:false   
    },
    C22P2:{
     type:String,
     required:true,
     default:false   
    },
    C22P3:{
     type:String,
     required:true,
     default:false   
    },
    C22P4:{
     type:String,
     required:true,
     default:false   
    },
    C23P1:{
     type:String,
     required:true,
     default:false   
    },
    C23P2:{
     type:String,
     required:true,
     default:false   
    },
    C23P3:{
     type:String,
     required:true,
     default:false   
    },
    C23P4:{
     type:String,
     required:true,
     default:false   
    },
    C24P1:{
     type:String,
     required:true,
     default:false   
    },
    C24P2:{
     type:String,
     required:true,
     default:false   
    },
    C24P3:{
     type:String,
     required:true,
     default:false   
    },
    C24P4:{
     type:String,
     required:true,
     default:false   
    },
    C25P1:{
     type:String,
     required:true,
     default:false   
    },
    C25P2:{
     type:String,
     required:true,
     default:false   
    },
    C25P3:{
     type:String,
     required:true,
     default:false   
    },
    C25P4:{
     type:String,
     required:true,
     default:false   
    },
    C26P1:{
     type:String,
     required:true,
     default:false   
    },
    C26P2:{
     type:String,
     required:true,
     default:false   
    },
    C26P3:{
     type:String,
     required:true,
     default:false   
    },
    C26P4:{
     type:String,
     required:true,
     default:false   
    },
    C27P1:{
     type:String,
     required:true,
     default:false   
    },
    C27P2:{
     type:String,
     required:true,
     default:false   
    },
    C27P3:{
     type:String,
     required:true,
     default:false   
    },
    C27P4:{
     type:String,
     required:true,
     default:false   
    },
    C28P1:{
     type:String,
     required:true,
     default:false   
    },
    C28P2:{
     type:String,
     required:true,
     default:false   
    },
    C28P3:{
     type:String,
     required:true,
     default:false   
    },
    C28P4:{
     type:String,
     required:true,
     default:false   
    },
    C29P1:{
     type:String,
     required:true,
     default:false   
    },
    C29P2:{
     type:String,
     required:true,
     default:false   
    },
    C29P3:{
     type:String,
     required:true,
     default:false   
    },
    C29P4:{
     type:String,
     required:true,
     default:false   
    },
})
module.exports = mongoose.model('Punto Dos Listado Peligros',puntoDosListadoPeligrosSchema);
