const mongoose = require('mongoose'),
    moment = require('moment');

const puntoDosResultadosRiesgosSchema = new mongoose.Schema({

    
  P1C1:{
    type:String,
    required:true,
    default:false  
  },
  P2C1:{
    type:String,
    required:true,
    default:false  
  },
  P3C1:{
    type:String,
    required:true,
    default:false  
  },
  P4C1:{
    type:String,
    required:true,
    default:false  
  },
  P5C1:{
   type:Boolean,
   required:true,
   default:false   
  },
  P6C1:{
   type:Boolean,
   required:true,
   default:false   
  },
  P7C1:{
   type:Boolean,
   required:true,
   default:false   
  },
  P1C2:{
    type:String,
    required:true,
    default:false   
  },
  P2C2:{
    type:String,
    required:true,
    default:false   
  },
  P3C2:{
    type:String,
    required:true,
    default:false   
  },
  P4C2:{
    type:String,
    required:true,
    default:false   
  },
  P5C2:{
   type:Boolean,
   required:true,
   default:false
  },
  P6C2:{
   type:Boolean,
   required:true,
   default:false
  },
  P7C2:{
   type:Boolean,
   required:true,
   default:false
  },
  P1C3:{
    type:String,
    required:true,
    default:false
  },
  P2C3:{
    type:String,
    required:true,
    default:false
  },
  P3C3:{
    type:String,
    required:true,
    default:false
  },
  P4C3:{
    type:String,
    required:true,
    default:false
  },
  P5C3:{
   type:Boolean,
   required:true,
   default:false
  },
  P6C3:{
   type:Boolean,
   required:true,
   default:false
  },
  P7C3:{
   type:Boolean,
   required:true,
   default:false
  },
  P1C4:{
    type:String,
    required:true,
    default:false   
  },
  P2C4:{
    type:String,
    required:true,
    default:false   
  },
  P3C4:{
    type:String,
    required:true,
    default:false   
  },
  P4C4:{
    type:String,
    required:true,
    default:false   
  },
  P5C4:{
   type:Boolean,
   required:true,
   default:false
  },
  P6C4:{
   type:Boolean,
   required:true,
   default:false
  },
  P7C4:{
   type:Boolean,
   required:true,
   default:false
  },
  P1C5:{
    type:String,
    required:true,
    default:false   
  },
  P2C5:{
    type:String,
    required:true,
    default:false   
  },
  P3C5:{
    type:String,
    required:true,
    default:false   
  },
  P4C5:{
    type:String,
    required:true,
    default:false   
  },
  P5C5:{
   type:Boolean,
   required:true,
   default:false
  },
  P6C5:{
   type:Boolean,
   required:true,
   default:false
  },
  P7C5:{
   type:Boolean,
   required:true,
   default:false
  },
  P1C6:{
    type:String,
    required:true,
    default:false   
  },
  P2C6:{
    type:String,
    required:true,
    default:false   
  },
  P3C6:{
    type:String,
    required:true,
    default:false   
  },
  P4C6:{
    type:String,
    required:true,
    default:false   
  },
  P5C6:{
   type:Boolean,
   required:true,
   default:false      
  },
  P6C6:{
   type:Boolean,
   required:true,
   default:false      
  },
  P7C6:{
   type:Boolean,
   required:true,
   default:false      
  },
  P1C7:{
    type:String,
    required:true,
    default:false   
  },
  P2C7:{
    type:String,
    required:true,
    default:false   
  },
  P3C7:{
    type:String,
    required:true,
    default:false   
  },
  P4C7:{
    type:String,
    required:true,
    default:false   
  },
  P5C7:{
   type:Boolean,
   required:true,
   default:false
  },
  P6C7:{
   type:Boolean,
   required:true,
   default:false
  },
  P7C7:{
   type:Boolean,
   required:true,
   default:false
  },
}) 

module.exports = mongoose.model("Punto Dos Resultados Riesgos",puntoDosResultadosRiesgosSchema)