const mongoose = require('mongoose'),
      moment = require('moment');

const punto7QuejaSugerencia = new mongoose.Schema({
    queja:{
        type:Boolean,
        required:true,
        default:false
    },
    sugerencias:{
        type:Boolean,
        required:true,
        default:false
    },
    SolicitudInformacion:{
        type:Boolean,
        required:true,
        default:false
    },
    condicionRiesgo:{
        type:Boolean,
        required:true,
        default:false
    },
    inpactoAmbiente:{
        type:String,
        required:true,
        default:false
    },
    descripcionMotivo:{
        type:String,
        required:true,
        default:false
    },
    nombre:{
        type:String,
        required:true,
        default:false
    },
    correoCelular:{
        type:String,
        required:true,
        default:false
    },
    consecutivo:{
        type:String,
        required:true,
        default:false
    },
    alta:{
        type:Boolean,
        required:true,
        default:false
    },
    media:{
        type:Boolean,
        required:true,
        default:false
    },
    baja:{
        type:Boolean,
        required:true,
        default:false
    },
    fecha:{
        type:Date,
        required:true,
        default:false
    }
});
module.exports = mongoose.model("Punto 7 Quejas Sugeracias",punto7QuejaSugerencia);