const mongoose = require('mongoose'),
      moment = require('moment');

const punto8ListaMaestraInternaSchema = new mongoose.Schema({
    
c1p1:{ 
    type:String,
    required:true,
    default:false},  
c1p2:{ 
    type:String,
    required:true,
    default:false},
c1p3:{ 
    type:String,
    required:true,
    default:false},
c1p4:{ 
    type:String,
    required:true,
    default:false},
c1p5:{ 
    type:String,
    required:true,
    default:false},
c1p6:{ 
    type:String,
    required:true,
    default:false},
c1p7:{ 
    type:String,
    required:true,
    default:false},
c1p8:{ 
    type:String,
    required:true,
    default:false},
c1p9:{ 
    type:String,
    required:true,
    default:false},
c2p1:{ 
    type:String,
    required:true,
    default:false},  
c2p2:{ 
    type:String,
    required:true,
    default:false},
c2p3:{ 
    type:String,
    required:true,
    default:false},
c2p4:{ 
    type:String,
    required:true,
    default:false},
c2p5:{ 
    type:String,
    required:true,
    default:false},
c2p6:{ 
    type:String,
    required:true,
    default:false},
c2p7:{ 
    type:String,
    required:true,
    default:false},
c2p8:{ 
    type:String,
    required:true,
    default:false},
c2p9:{ 
    type:String,
    required:true,
    default:false},
c3p1:{ 
    type:String,
    required:true,
    default:false},  
c3p2:{ 
    type:String,
    required:true,
    default:false},
c3p3:{ 
    type:String,
    required:true,
    default:false},
c3p4:{ 
    type:String,
    required:true,
    default:false},
c3p5:{ 
    type:String,
    required:true,
    default:false},
c3p6:{ 
    type:String,
    required:true,
    default:false},
c3p7:{ 
    type:String,
    required:true,
    default:false},
c3p8:{ 
    type:String,
    required:true,
    default:false},
c3p9:{ 
    type:String,
    required:true,
    default:false},
c4p1:{ 
    type:String,
    required:true,
    default:false},  
c4p2:{ 
    type:String,
    required:true,
    default:false},
c4p3:{ 
    type:String,
    required:true,
    default:false},
c4p4:{ 
    type:String,
    required:true,
    default:false},
c4p5:{ 
    type:String,
    required:true,
    default:false},
c4p6:{ 
    type:String,
    required:true,
    default:false},
c4p7:{ 
    type:String,
    required:true,
    default:false},
c4p8:{ 
    type:String,
    required:true,
    default:false},
c4p9:{ 
    type:String,
    required:true,
    default:false},
c5p1:{ 
    type:String,
    required:true,
    default:false},  
c5p2:{ 
    type:String,
    required:true,
    default:false},
c5p3:{ 
    type:String,
    required:true,
    default:false},
c5p4:{ 
    type:String,
    required:true,
    default:false},
c5p5:{ 
    type:String,
    required:true,
    default:false},
c5p6:{ 
    type:String,
    required:true,
    default:false},
c5p7:{ 
    type:String,
    required:true,
    default:false},
c5p8:{ 
    type:String,
    required:true,
    default:false},
c5p9:{ 
    type:String,
    required:true,
    default:false},
c6p1:{ 
    type:String,
    required:true,
    default:false},  
c6p2:{ 
    type:String,
    required:true,
    default:false},
c6p3:{ 
    type:String,
    required:true,
    default:false},
c6p4:{ 
    type:String,
    required:true,
    default:false},
c6p5:{ 
    type:String,
    required:true,
    default:false},
c6p6:{ 
    type:String,
    required:true,
    default:false},
c6p7:{ 
    type:String,
    required:true,
    default:false},
c6p8:{ 
    type:String,
    required:true,
    default:false},
c6p9:{ 
    type:String,
    required:true,
    default:false},
c7p1:{ 
    type:String,
    required:true,
    default:false},  
c7p2:{ 
    type:String,
    required:true,
    default:false},
c7p3:{ 
    type:String,
    required:true,
    default:false},
c7p4:{ 
    type:String,
    required:true,
    default:false},
c7p5:{ 
    type:String,
    required:true,
    default:false},
c7p6:{ 
    type:String,
    required:true,
    default:false},
c7p7:{ 
    type:String,
    required:true,
    default:false},
c7p8:{ 
    type:String,
    required:true,
    default:false},
c7p9:{ 
    type:String,
    required:true,
    default:false},
c8p1:{ 
    type:String,
    required:true,
    default:false},  
c8p2:{ 
    type:String,
    required:true,
    default:false},
c8p3:{ 
    type:String,
    required:true,
    default:false},
c8p4:{ 
    type:String,
    required:true,
    default:false},
c8p5:{ 
    type:String,
    required:true,
    default:false},
c8p6:{ 
    type:String,
    required:true,
    default:false},
c8p7:{ 
    type:String,
    required:true,
    default:false},
c8p8:{ 
    type:String,
    required:true,
    default:false},
c8p9:{ 
    type:String,
    required:true,
    default:false},
c9p1:{ 
    type:String,
    required:true,
    default:false},  
c9p2:{ 
    type:String,
    required:true,
    default:false},
c9p3:{ 
    type:String,
    required:true,
    default:false},
c9p4:{ 
    type:String,
    required:true,
    default:false},
c9p5:{ 
    type:String,
    required:true,
    default:false},
c9p6:{ 
    type:String,
    required:true,
    default:false},
c9p7:{ 
    type:String,
    required:true,
    default:false},
c9p8:{ 
    type:String,
    required:true,
    default:false},
c9p9:{ 
    type:String,
    required:true,
    default:false},
c10p1:{ 
    type:String,
    required:true,
    default:false},  
c10p2:{ 
    type:String,
    required:true,
    default:false},
c10p3:{ 
    type:String,
    required:true,
    default:false},
c10p4:{ 
    type:String,
    required:true,
    default:false},
c10p5:{ 
    type:String,
    required:true,
    default:false},
c10p6:{ 
    type:String,
    required:true,
    default:false},
c10p7:{ 
    type:String,
    required:true,
    default:false},
c10p8:{ 
    type:String,
    required:true,
    default:false},
c10p9:{ 
    type:String,
    required:true,
    default:false},
c11p1:{ 
    type:String,
    required:true,
    default:false},  
c11p2:{ 
    type:String,
    required:true,
    default:false},
c11p3:{ 
    type:String,
    required:true,
    default:false},
c11p4:{ 
    type:String,
    required:true,
    default:false},
c11p5:{ 
    type:String,
    required:true,
    default:false},
c11p6:{ 
    type:String,
    required:true,
    default:false},
c11p7:{ 
    type:String,
    required:true,
    default:false},
c11p8:{ 
    type:String,
    required:true,
    default:false},
c11p9:{ 
    type:String,
    required:true,
    default:false},
c12p1:{ 
    type:String,
    required:true,
    default:false},  
c12p2:{ 
    type:String,
    required:true,
    default:false},
c12p3:{ 
    type:String,
    required:true,
    default:false},
c12p4:{ 
    type:String,
    required:true,
    default:false},
c12p5:{ 
    type:String,
    required:true,
    default:false},
c12p6:{ 
    type:String,
    required:true,
    default:false},
c12p7:{ 
    type:String,
    required:true,
    default:false},
c12p8:{ 
    type:String,
    required:true,
    default:false},
c12p9:{ 
    type:String,
    required:true,
    default:false},
c13p1:{ 
    type:String,
    required:true,
    default:false
},  
c13p2:{ 
    type:String,
    required:true,
    default:false
},
c13p3:{ 
    type:String,
    required:true,
    default:false
},
c13p4:{ 
    type:String,
    required:true,
    default:false
},
c13p5:{ 
    type:String,
    required:true,
    default:false
},
c13p6:{ 
    type:String,
    required:true,
    default:false
},
c13p7:{ 
    type:String,
    required:true,
    default:false
},
c13p8:{ 
    type:String,
    required:true,
    default:false
},
c13p9:{ 
    type:String,
    required:true,
    default:false
},
c13p10:{ 
    type:String,
    required:true,
    default:false
},  
c13p11:{ 
    type:String,
    required:true,
    default:false
},
c13p12:{ 
    type:String,
    required:true,
    default:false
},
c13p13:{ 
    type:String,
    required:true,
    default:false
},
c13p14:{ 
    type:String,
    required:true,
    default:false
},
c13p15:{ 
    type:String,
    required:true,
    default:false
},
c14p1:{ 
    type:String,
    required:true,
    default:false
},  
c14p2:{ 
    type:String,
    required:true,
    default:false
},
c14p3:{ 
    type:String,
    required:true,
    default:false
},
c14p4:{ 
    type:String,
    required:true,
    default:false
},
c14p5:{ 
    type:String,
    required:true,
    default:false
},
c14p6:{ 
    type:String,
    required:true,
    default:false
},
c14p7:{ 
    type:String,
    required:true,
    default:false
},
c14p8:{ 
    type:String,
    required:true,
    default:false
},
c14p9:{ 
    type:String,
    required:true,
    default:false
},
c14p10:{ 
    type:String,
    required:true,
    default:false
},  
c14p11:{ 
    type:String,
    required:true,
    default:false
},
c14p12:{ 
    type:String,
    required:true,
    default:false
},
c14p13:{ 
    type:String,
    required:true,
    default:false
},
c14p14:{ 
    type:String,
    required:true,
    default:false
},
c14p15:{ 
    type:String,
    required:true,
    default:false
},
c15p1: {
    type:String,
    required:true,
    default:false
},  
c15p2: {
    type:String,
    required:true,
    default:false
},
c15p3: {
    type:String,
    required:true,
    default:false
},
c15p4: {
    type:String,
    required:true,
    default:false
},
c15p5: {
    type:String,
    required:true,
    default:false
},
c15p6: {
    type:String,
    required:true,
    default:false
},
c15p7: {
    type:String,
    required:true,
    default:false
},
c15p8: {
    type:String,
    required:true,
    default:false
},
c15p9: {
    type:String,
    required:true,
    default:false
},
c15p10: {
    type:String,
    required:true,
    default:false
},  
c15p11: {
    type:String,
    required:true,
    default:false
},
c15p12: {
    type:String,
    required:true,
    default:false
},
c15p13: {
    type:String,
    required:true,
    default:false
},
c15p14: {
    type:String,
    required:true,
    default:false
},
c15p15: {
    type:String,
    required:true,
    default:false
},
c16p1:{
    type:String,
    required:true,
    default:false
},  
c16p2:{
    type:String,
    required:true,
    default:false
},
c16p3:{
    type:String,
    required:true,
    default:false
},
c16p4:{
    type:String,
    required:true,
    default:false
},
c16p5:{
    type:String,
    required:true,
    default:false
},
c16p6:{
    type:String,
    required:true,
    default:false
},
c16p7:{
    type:String,
    required:true,
    default:false
},
c16p8:{
    type:String,
    required:true,
    default:false
},
c16p9:{
    type:String,
    required:true,
    default:false
},
c16p10:{
    type:String,
    required:true,
    default:false
},  
c16p11:{
    type:String,
    required:true,
    default:false
},
c16p12:{
    type:String,
    required:true,
    default:false
},
c16p13:{
    type:String,
    required:true,
    default:false
},
c16p14:{
    type:String,
    required:true,
    default:false
},
c16p15:{
    type:String,
    required:true,
    default:false
},
c17p1:{
    type:String,
    required:true,
    default:false
},  
c17p2:{
    type:String,
    required:true,
    default:false
},
c17p3:{
    type:String,
    required:true,
    default:false
},
c17p4:{
    type:String,
    required:true,
    default:false
},
c17p5:{
    type:String,
    required:true,
    default:false
},
c17p6:{
    type:String,
    required:true,
    default:false
},
c17p7:{
    type:String,
    required:true,
    default:false
},
c17p8:{
    type:String,
    required:true,
    default:false
},
c17p9:{
    type:String,
    required:true,
    default:false
},
c17p10:{
    type:String,
    required:true,
    default:false
},  
c17p11:{
    type:String,
    required:true,
    default:false
},
c17p12:{
    type:String,
    required:true,
    default:false
},
c17p13:{
    type:String,
    required:true,
    default:false
},
c17p14:{
    type:String,
    required:true,
    default:false
},
c17p15:{
    type:String,
    required:true,
    default:false
},
c18p1:{
    type:String,
    required:true,
    default:false
},  
c18p2:{
    type:String,
    required:true,
    default:false
},
c18p3:{
    type:String,
    required:true,
    default:false
},
c18p4:{
    type:String,
    required:true,
    default:false
},
c18p5:{
    type:String,
    required:true,
    default:false
},
c18p6:{
    type:String,
    required:true,
    default:false
},
c18p7:{
    type:String,
    required:true,
    default:false
},
c18p8:{
    type:String,
    required:true,
    default:false
},
c18p9:{
    type:String,
    required:true,
    default:false
},
c18p10:{
    type:String,
    required:true,
    default:false
},  
c18p11:{
    type:String,
    required:true,
    default:false
},
c18p12:{
    type:String,
    required:true,
    default:false
},
c18p13:{
    type:String,
    required:true,
    default:false
},
c18p14:{
    type:String,
    required:true,
    default:false
},
c18p15:{
    type:String,
    required:true,
    default:false
},
c19p1:{
    type:String,
    required:true,
    default:false
},  
c19p2:{
    type:String,
    required:true,
    default:false
},
c19p3:{
    type:String,
    required:true,
    default:false
},
c19p4:{
    type:String,
    required:true,
    default:false
},
c19p5:{
    type:String,
    required:true,
    default:false
},
c19p6:{
    type:String,
    required:true,
    default:false
},
c19p7:{
    type:String,
    required:true,
    default:false
},
c19p8:{
    type:String,
    required:true,
    default:false
},
c19p9:{
    type:String,
    required:true,
    default:false
},
c19p10:{
    type:String,
    required:true,
    default:false
},  
c19p11:{
    type:String,
    required:true,
    default:false
},
c19p12:{
    type:String,
    required:true,
    default:false
},
c19p13:{
    type:String,
    required:true,
    default:false
},
c19p14:{
    type:String,
    required:true,
    default:false
},
c19p15:{
    type:String,
    required:true,
    default:false
},
c20p1:{
    type:String,
    required:true,
    default:false
},  
c20p2:{
    type:String,
    required:true,
    default:false
},
c20p3:{
    type:String,
    required:true,
    default:false
},
c20p4:{
    type:String,
    required:true,
    default:false
},
c20p5:{
    type:String,
    required:true,
    default:false
},
c20p6:{
    type:String,
    required:true,
    default:false
},
c20p7:{
    type:String,
    required:true,
    default:false
},
c20p8:{
    type:String,
    required:true,
    default:false
},
c20p9:{
    type:String,
    required:true,
    default:false
},
c20p10:{
    type:String,
    required:true,
    default:false
},  
c20p11:{
    type:String,
    required:true,
    default:false
},
c20p12:{
    type:String,
    required:true,
    default:false
},
c20p13:{
    type:String,
    required:true,
    default:false
},
c20p14:{
    type:String,
    required:true,
    default:false
},
c20p15:{
    type:String,
    required:true,
    default:false
},
c21p1:{
    type:String,
    required:true,
    default:false
},  
c21p2:{
    type:String,
    required:true,
    default:false
},
c21p3:{
    type:String,
    required:true,
    default:false
},
c21p4:{
    type:String,
    required:true,
    default:false
},
c21p5:{
    type:String,
    required:true,
    default:false
},
c21p6:{
    type:String,
    required:true,
    default:false
},
c21p7:{
    type:String,
    required:true,
    default:false
},
c21p8:{
    type:String,
    required:true,
    default:false
},
c21p9:{
    type:String,
    required:true,
    default:false
},
c21p10:{
    type:String,
    required:true,
    default:false
},  
c21p11:{
    type:String,
    required:true,
    default:false
},
c21p12:{
    type:String,
    required:true,
    default:false
},
c21p13:{
    type:String,
    required:true,
    default:false
},
c21p14:{
    type:String,
    required:true,
    default:false
},
c21p15:{
    type:String,
    required:true,
    default:false
},
c22p1:{
    type:String,
    required:true,
    default:false
},  
c22p2:{
    type:String,
    required:true,
    default:false
},
c22p3:{
    type:String,
    required:true,
    default:false
},
c22p4:{
    type:String,
    required:true,
    default:false
},
c22p5:{
    type:String,
    required:true,
    default:false
},
c22p6:{
    type:String,
    required:true,
    default:false
},
c22p7:{
    type:String,
    required:true,
    default:false
},
c22p8:{
    type:String,
    required:true,
    default:false
},
c22p9:{
    type:String,
    required:true,
    default:false
},
c22p10:{
    type:String,
    required:true,
    default:false
},  
c22p11:{
    type:String,
    required:true,
    default:false
},
c22p12:{
    type:String,
    required:true,
    default:false
},
c22p13:{
    type:String,
    required:true,
    default:false
},
c22p14:{
    type:String,
    required:true,
    default:false
},
c22p15:{
    type:String,
    required:true,
    default:false
},
c23p1:{
    type:String,
    required:true,
    default:false
},  
c23p2:{
    type:String,
    required:true,
    default:false
},
c23p3:{
    type:String,
    required:true,
    default:false
},
c23p4:{
    type:String,
    required:true,
    default:false
},
c23p5:{
    type:String,
    required:true,
    default:false
},
c23p6:{
    type:String,
    required:true,
    default:false
},
c23p7:{
    type:String,
    required:true,
    default:false
},
c23p8:{
    type:String,
    required:true,
    default:false
},
c23p9:{
    type:String,
    required:true,
    default:false
},
c23p10:{
    type:String,
    required:true,
    default:false
},  
c23p11:{
    type:String,
    required:true,
    default:false
},
c23p12:{
    type:String,
    required:true,
    default:false
},
c23p13:{
    type:String,
    required:true,
    default:false
},
c23p14:{
    type:String,
    required:true,
    default:false
},
c23p15:{
    type:String,
    required:true,
    default:false
},
c24p1:{
    type:String,
    required:true,
    default:false
},  
c24p2:{
    type:String,
    required:true,
    default:false
},
c24p3:{
    type:String,
    required:true,
    default:false
},
c24p4:{
    type:String,
    required:true,
    default:false
},
c24p5:{
    type:String,
    required:true,
    default:false
},
c24p6:{
    type:String,
    required:true,
    default:false
},
c24p7:{
    type:String,
    required:true,
    default:false
},
c24p8:{
    type:String,
    required:true,
    default:false
},
c24p9:{
    type:String,
    required:true,
    default:false
},
c24p10:{
    type:String,
    required:true,
    default:false
},  
c24p11:{
    type:String,
    required:true,
    default:false
},
c24p12:{
    type:String,
    required:true,
    default:false
},
c24p13:{
    type:String,
    required:true,
    default:false
},
c24p14:{
    type:String,
    required:true,
    default:false
},
c24p15:{
    type:String,
    required:true,
    default:false
},
c25p1:{
    type:String,
    required:true,
    default:false
},  
c25p2:{
    type:String,
    required:true,
    default:false
},
c25p3:{
    type:String,
    required:true,
    default:false
},
c25p4:{
    type:String,
    required:true,
    default:false
},
c25p5:{
    type:String,
    required:true,
    default:false
},

})
module.exports = mongoose.model("Punto 8 Copetencia Personal",punto8ListaMaestraInternaSchema)