const mongoose = require('mongoose'),
      moment = require('moment');

const punto8SolicitudCambioSchema = new mongoose.Schema({
    codificacion:{ 
        type:String,
        required:true,
        default:false
    },
    nombreDocumento:{ 
        type:String,
        required:true,
        default:false
    },
    elementoSistema:{ 
        type:String,
        required:true,
        default:false
    },
    nombreSolicitan:{ 
        type:String,
        required:true,
        default:false
    },
    fechaSolicitud:{ 
        type:String,
        required:true,
        default:false
    },
    estadoual:{ 
        type:String,
        required:true,
        default:false
    },
    cambioPropuesto:{ 
        type:String,
        required:true,
        default:false
    },
    motivoAceptacion:{ 
        type:String,
        required:true,
        default:false
    },
    puesto:{ 
        type:String,
        required:true,
        default:false
    },
    c1C1:{ 
        type:Boolean,
        required:true,
        default:false
    },
    c1C2:{ 
        type:Boolean,
        required:true,
        default:false
    },
    c1C3:{ 
        type:Boolean,
        required:true,
        default:false
    },
    c1C4:{ 
        type:Boolean,
        required:true,
        default:false
    },
    c2C1:{ 
        type:Boolean,
        required:true,
        default:false
    },
    c2C2:{ 
        type:Boolean,
        required:true,
        default:false
    },
    c2C3:{ 
        type:Boolean,
        required:true,
        default:false
    },
    c2C4:{ 
        type:Boolean,
        required:true,
        default:false
    },
    c2C5:{ 
        type:Boolean,
        required:true,
        default:false
    },
    c3C1:{ 
        type:Boolean,
        required:true,
        default:false
    },
    c3C2:{ 
        type:Boolean,
        required:true,
        default:false
    },
})
module.exports = mongoose.model("Punto 6 Copetencia Personal",punto8SolicitudCambioSchema)