const mongoose = require('mongoose'),
      moment = require('moment');

const punto11EdificiosSchema = new mongoose.Schema({
    c1C1:{ 
        type:Boolean,
        required:true,
        default:false
    },
    c2C1:{ 
        type:Boolean,
        required:true,
        default:false
    },
    c3C1:{ 
        type:Boolean,
        required:true,
        default:false
    },
    c4C1:{ 
        type:Boolean,
        required:true,
        default:false
    },
    c5C1:{ 
        type:Boolean,
        required:true,
        default:false
    },
    c6C1:{ 
        type:Boolean,
        required:true,
        default:false
    },
    c7C1:{ 
        type:Boolean,
        required:true,
        default:false
    },
    c8C1:{ 
        type:Boolean,
        required:true,
        default:false
    },
    c9C1:{ 
        type:Boolean,
        required:true,
        default:false
    },
    c10C1:{ 
        type:Boolean,
        required:true,
        default:false
    },
    c11C1:{ 
        type:Boolean,
        required:true,
        default:false
    },
    c12C1:{ 
        type:Boolean,
        required:true,
        default:false
    },
    c1C2:{ 
        type:Boolean,
        required:true,
        default:false
    },
    c2C2:{ 
        type:Boolean,
        required:true,
        default:false
    },
    c3C2:{ 
        type:Boolean,
        required:true,
        default:false
    },
    c4C2:{ 
        type:Boolean,
        required:true,
        default:false
    },
    c5C2:{ 
        type:Boolean,
        required:true,
        default:false
    },
    c6C2:{ 
        type:Boolean,
        required:true,
        default:false
    },
    c7C2:{ 
        type:Boolean,
        required:true,
        default:false
    },
    c8C2:{ 
        type:Boolean,
        required:true,
        default:false
    },
    c9C2:{ 
        type:Boolean,
        required:true,
        default:false
    },
    c10C2:{ 
        type:Boolean,
        required:true,
        default:false
    },
    c11C2:{ 
        type:Boolean,
        required:true,
        default:false
    },
    c12C2:{ 
        type:Boolean,
        required:true,
        default:false
    },
    c1C3:{ 
        type:Boolean,
        required:true,
        default:false
    },
    c2C3:{ 
        type:Boolean,
        required:true,
        default:false
    },
    c3C3:{ 
        type:Boolean,
        required:true,
        default:false
    },
    c4C3:{ 
        type:Boolean,
        required:true,
        default:false
    },
    c5C3:{ 
        type:Boolean,
        required:true,
        default:false
    },
    c6C3:{ 
        type:Boolean,
        required:true,
        default:false
    },
    c7C3:{ 
        type:Boolean,
        required:true,
        default:false
    },
    c8C3:{ 
        type:Boolean,
        required:true,
        default:false
    },
    c9C3:{ 
        type:Boolean,
        required:true,
        default:false
    },
    c10C3:{ 
        type:Boolean,
        required:true,
        default:false
    },
    c11C3:{ 
        type:Boolean,
        required:true,
        default:false
    },
    c12C3:{ 
        type:Boolean,
        required:true,
        default:false
    },
    c1C4:{ 
        type:Boolean,
        required:true,
        default:false
    },
    c2C4:{ 
        type:Boolean,
        required:true,
        default:false
    },
    c3C4:{ 
        type:Boolean,
        required:true,
        default:false
    },
    c4C4:{ 
        type:Boolean,
        required:true,
        default:false
    },
    c5C4:{ 
        type:Boolean,
        required:true,
        default:false
    },
    c6C4:{ 
        type:Boolean,
        required:true,
        default:false
    },
    c7C4:{ 
        type:Boolean,
        required:true,
        default:false
    },
    c8C4:{ 
        type:Boolean,
        required:true,
        default:false
    },
    c9C4:{ 
        type:Boolean,
        required:true,
        default:false
    },
    c10C4:{ 
        type:Boolean,
        required:true,
        default:false
    },
    c11C4:{ 
        type:Boolean,
        required:true,
        default:false
    },
    c12C4:{ 
        type:Boolean,
        required:true,
        default:false
    },
    c1C5:{ 
        type:Boolean,
        required:true,
        default:false
    },
    c2C5:{ 
        type:Boolean,
        required:true,
        default:false
    },
    c3C5:{ 
        type:Boolean,
        required:true,
        default:false
    },
    c4C5:{ 
        type:Boolean,
        required:true,
        default:false
    },
    c5C5:{ 
        type:Boolean,
        required:true,
        default:false
    },
    c6C5:{ 
        type:Boolean,
        required:true,
        default:false
    },
    c7C5:{ 
        type:Boolean,
        required:true,
        default:false
    },
    c8C5:{ 
        type:Boolean,
        required:true,
        default:false
    },
    c9C5:{ 
        type:Boolean,
        required:true,
        default:false
    },
    c10C5:{ 
        type:Boolean,
        required:true,
        default:false
    },
    c11C5:{ 
        type:Boolean,
        required:true,
        default:false
    },
    c12C5:{ 
        type:Boolean,
        required:true,
        default:false
    },
    c1C6:{ 
        type:Boolean,
        required:true,
        default:false
    },
    c2C6:{ 
        type:Boolean,
        required:true,
        default:false
    },
    c3C6:{ 
        type:Boolean,
        required:true,
        default:false
    },
    c4C6:{ 
        type:Boolean,
        required:true,
        default:false
    },
    c5C6:{ 
        type:Boolean,
        required:true,
        default:false
    },
    c6C6:{ 
        type:Boolean,
        required:true,
        default:false
    },
    c7C6:{ 
        type:Boolean,
        required:true,
        default:false
    },
    c8C6:{ 
        type:Boolean,
        required:true,
        default:false
    },
    c9C6:{ 
        type:Boolean,
        required:true,
        default:false
    },
    c10C6:{ 
        type:Boolean,
        required:true,
        default:false
    },
    c11C6:{ 
        type:Boolean,
        required:true,
        default:false
    },
    c12C6:{ 
        type:Boolean,
        required:true,
        default:false
    },
    c1C7:{ 
        type:Boolean,
        required:true,
        default:false
    },
    c2C7:{ 
        type:Boolean,
        required:true,
        default:false
    },
    c3C7:{ 
        type:Boolean,
        required:true,
        default:false
    },
    c4C7:{ 
        type:Boolean,
        required:true,
        default:false
    },
    c5C7:{ 
        type:Boolean,
        required:true,
        default:false
    },
    c6C7:{ 
        type:Boolean,
        required:true,
        default:false
    },
    c7C7:{ 
        type:Boolean,
        required:true,
        default:false
    },
    c8C7:{ 
        type:Boolean,
        required:true,
        default:false
    },
    c9C7:{ 
        type:Boolean,
        required:true,
        default:false
    },
    c10C7:{ 
        type:Boolean,
        required:true,
        default:false
    },
    c11C7:{ 
        type:Boolean,
        required:true,
        default:false
    },
    c12C7:{ 
        type:Boolean,
        required:true,
        default:false
    },
    c1C8:{ 
        type:Boolean,
        required:true,
        default:false
    },
    c2C8:{ 
        type:Boolean,
        required:true,
        default:false
    },
    c3C8:{ 
        type:Boolean,
        required:true,
        default:false
    },
    c4C8:{ 
        type:Boolean,
        required:true,
        default:false
    },
    c5C8:{ 
        type:Boolean,
        required:true,
        default:false
    },
    c6C8:{ 
        type:Boolean,
        required:true,
        default:false
    },
    c7C8:{ 
        type:Boolean,
        required:true,
        default:false
    },
    c8C8:{ 
        type:Boolean,
        required:true,
        default:false
    },
    c9C8:{ 
        type:Boolean,
        required:true,
        default:false
    },
    c10C8:{ 
        type:Boolean,
        required:true,
        default:false
    },
    c11C8:{ 
        type:Boolean,
        required:true,
        default:false
    },
    c12C8:{ 
        type:Boolean,
        required:true,
        default:false
    },
    c1C9:{ 
        type:Boolean,
        required:true,
        default:false
    },
    c2C9:{ 
        type:Boolean,
        required:true,
        default:false
    },
    c3C9:{ 
        type:Boolean,
        required:true,
        default:false
    },
    c4C9:{ 
        type:Boolean,
        required:true,
        default:false
    },
    c5C9:{ 
        type:Boolean,
        required:true,
        default:false
    },
    c6C9:{ 
        type:Boolean,
        required:true,
        default:false
    },
    c7C9:{ 
        type:Boolean,
        required:true,
        default:false
    },
    c8C9:{ 
        type:Boolean,
        required:true,
        default:false
    },
    c9C9:{ 
        type:Boolean,
        required:true,
        default:false
    },
    c10C9:{ 
        type:Boolean,
        required:true,
        default:false
    },
    c11C9:{ 
        type:Boolean,
        required:true,
        default:false
    },
    c12C9:{ 
        type:Boolean,
        required:true,
        default:false
    },
    c1C10:{ 
        type:Boolean,
        required:true,
        default:false
    },
    c2C10:{ 
        type:Boolean,
        required:true,
        default:false
    },
    c3C10:{ 
        type:Boolean,
        required:true,
        default:false
    },
    c4C10:{ 
        type:Boolean,
        required:true,
        default:false
    },
    c5C10:{ 
        type:Boolean,
        required:true,
        default:false
    },
    c6C10:{ 
        type:Boolean,
        required:true,
        default:false
    },
    c7C10:{ 
        type:Boolean,
        required:true,
        default:false
    },
    c8C10:{ 
        type:Boolean,
        required:true,
        default:false
    },
    c9C10:{ 
        type:Boolean,
        required:true,
        default:false
    },
    c10C10:{ 
        type:Boolean,
        required:true,
        default:false
    },
    c11C10:{ 
        type:Boolean,
        required:true,
        default:false
    },
    c12C10:{ 
        type:Boolean,
        required:true,
        default:false
    },
    c1C11:{ 
        type:Boolean,
        required:true,
        default:false
    },
    c2C11:{ 
        type:Boolean,
        required:true,
        default:false
    },
    c3C11:{ 
        type:Boolean,
        required:true,
        default:false
    },
    c4C11:{ 
        type:Boolean,
        required:true,
        default:false
    },
    c5C11:{ 
        type:Boolean,
        required:true,
        default:false
    },
    c6C11:{ 
        type:Boolean,
        required:true,
        default:false
    },
    c7C11:{ 
        type:Boolean,
        required:true,
        default:false
    },
    c8C11:{ 
        type:Boolean,
        required:true,
        default:false
    },
    c9C11:{ 
        type:Boolean,
        required:true,
        default:false
    },
    c10C11:{ 
        type:Boolean,
        required:true,
        default:false
    },
    c11C11:{ 
        type:Boolean,
        required:true,
        default:false
    },
    c12C11:{ 
        type:Boolean,
        required:true,
        default:false
    },
    c1C12:{ 
        type:Boolean,
        required:true,
        default:false
    },
    c2C12:{ 
        type:Boolean,
        required:true,
        default:false
    },
    c3C12:{ 
        type:Boolean,
        required:true,
        default:false
    },
    c4C12:{ 
        type:Boolean,
        required:true,
        default:false
    },
    c5C12:{ 
        type:Boolean,
        required:true,
        default:false
    },
    c6C12:{ 
        type:Boolean,
        required:true,
        default:false
    },
    c7C12:{ 
        type:Boolean,
        required:true,
        default:false
    },
    c8C12:{ 
        type:Boolean,
        required:true,
        default:false
    },
    c9C12:{ 
        type:Boolean,
        required:true,
        default:false
    },
    c10C12:{ 
        type:Boolean,
        required:true,
        default:false
    },
    c11C12:{ 
        type:Boolean,
        required:true,
        default:false
    },
    c12C12:{ 
        type:Boolean,
        required:true,
        default:false
    },

})
module.exports = mongoose.model("Punto 11 mantenimiento de edificios",punto11EdificiosSchema)