const mongoose = require('mongoose'),
      moment = require('moment');


const puntoochoSchema = new mongoose.Schema({
    politica: {
        type: Boolean,
        required: true,
        default: false
    },
    identificacioPeligros:{
        type: Boolean,
        required: true,
        default: false
    },
    objetivosMetas:{
        type: Boolean,
        require:true,
        default:false
    },
    funcionesResponsabilidades:{
        type:Boolean,
        require:true,
        default:false
    },
    copetenciaPersonal:{
        type:Boolean,
        require:true,
        default:false
    },
    comunicacionParticipacion:{
        type:Boolean,
        require:true,
        default:false
    },
    controlDocumentos:{
        type:Boolean,
        require:true,
        default:false
    },
    mejoresPracticas:{
        type:Boolean,
        require:true,
        default:false
    },
    controlActividades:{
        type:Boolean,
        require:true,
        default:false
    },
    integridadMecanica:{
        type:Boolean,
        require:true,
        default:false
    },
    seguridadContratistas:{
        type:Boolean,
        require:true,
        default:false
    },
    respuestasEmergencias:{
        type:Boolean,
        require:true,
        default:false
    },
    monitoreoVerificacion:{
        type:Boolean,
        require:true,
        default:false
    },
    auditorias:{
        type:Boolean,
        require:true,
        default:false
    },
    investigacionAccidente:{
        type:Boolean,
        require:true,
        default:false
    },
    revisionResultados:{
        type:Boolean,
        require:true,
        default:false
    },
    informeDesempeño:{
        type:Boolean,
        require:true,
        default:false
    },
    receocionAutotanque:{
        type:Boolean,
        require:true,
        default:false
    },
    despachoProductos:{
        type:Boolean,
        require:true,
        default:false
    },
    lineasElectricas:{
        type:Boolean,
        require:true,
        default:false
    },
    lineasProducto:{
        type:Boolean,
        require:true,
        default:false
    },
    fuentesIgnicion:{
        type:Boolean,
        require:true,
        default:false
    },
    trabajoEscaleras:{
        type:Boolean,
        require:true,
        default:false
    },
    trabajoAreasConfinadas:{
        type:Boolean,
        require:true,
        default:false
    },
    permisoTrabajoPeligroso:{
        type:Boolean,
        require:true,
        default:false
    },
    administracionCambioTecnologia:{
        type:Boolean,
        require:true,
        default:false
    },
    mantenimientoDispensarios:{
        type:Boolean,
        require:true,
        default:false
    },
    mantenimientoTanques:{
        type:Boolean,
        require:true,
        default:false
    },
    mantenimientoElectricos:{
        type:Boolean,
        require:true,
        default:false
    },
    mantenimientoEdificios:{
        type:Boolean,
        require:true,
        default:false
    },
    mantenimientoDrenajes:{
        type:Boolean,
        require:true,
        default:false
    },
    mantenimientoMaquinas:{
        type:Boolean,
        require:true,
        default:false
    },
    planesEmergencia:{
        type:Boolean,
        require:true,
        default:false
    },
    metodologiaArbolFallas:{
        type:Boolean,
        require:true,
        default:false
    },
    procedimientoPracticas:{
        type:Boolean,
        require:true,
        default:false
    },
    listaDocumentosInternos:{
        type:Boolean,
        require:true,
        default:false
    },
    solicitudCambios:{
        type:Boolean,
        require:true,
        default:false
    },
    listaDistribucionDocumentos:{
        type:Boolean,
        require:true,
        default:false
    },
    listaComunicacion:{
        type:Boolean,
        require:true,
        default:false
    },
    quejasSugerencias:{
        type:Boolean,
        require:true,
        default:false
    },
    evaluacionAspectoAmbiental:{
        type:Boolean,
        require:true,
        default:false
    },
    evaluacionRiesgos:{
        type:Boolean,
        require:true,
        default:false
    },
    resultadoAnalisisRiesgos:{
        type:Boolean,
        require:true,
        default:false
    },
    listadoRiesgosAspectosAmbientales:{
        type:Boolean,
        require:true,
        default:false
    },
    objetivosMetaIndicadores:{
        type:Boolean,
        require:true,
        default:false
    },
    matrizResponsabilidad:{
        type:Boolean,
        require:true,
        default:false
    },
    perfilPuestoTrabajo:{
        type:Boolean,
        require:true,
        default:false
    },
    detaccionNecesidadesCapacitacion:{
        type:Boolean,
        require:true,
        default:false
    },
    programaCapacitacion:{
        type:Boolean,
        require:true,
        default:false
    },
    listadoCodigosEstandares:{
        type:Boolean,
        require:true,
        default:false
    },
    administracionCambioTecnologia:{
        type:Boolean,
        require:true,
        default:false
    },
    programacionMantenimiento:{
        type:Boolean,
        require:true,
        default:false
    },
    listadoEquipoCritico:{
        type:Boolean,
        require:true,
        default:false
    },
    listadoRequisitosLegales:{
        type:Boolean,
        require:true,
        default:false
    },
    anexoSeguridadContratistas:{
        type:Boolean,
        require:true,
        default:false
    },
    actaIntegracionBrigadas:{
        type:Boolean,
        require:true,
        default:false
    },
    programaSimulacros:{
        type:Boolean,
        require:true,
        default:false
    },
    planeacionSimulacros:{
        type:Boolean,
        require:true,
        default:false
    },
    EvaluacionSimulacros:{
        type:Boolean,
        require:true,
        default:false
    },
    programaMonitoreoMedicion:{
        type:Boolean,
        require:true,
        default:false
    },
    resultadosMonitoreoParametros:{
        type:Boolean,
        require:true,
        default:false
    },
    evaluacionCumplimientoRequisitos:{
        type:Boolean,
        require:true,
        default:false
    },
    resultadosMonitoreosParametrosDesempeño:{
        type:Boolean,
        require:true,
        default:false
    },
    evaluacionCumplimientoRequisitosLegales:{
        type:Boolean,
        require:true,
        default:false
    },
    planAtencion:{
        type:Boolean,
        require:true,
        default:false
    },
    programaAuditorias:{
        type:Boolean,
        require:true,
        default:false
    },
    planAuditoria:{
        type:Boolean,
        require:true,
        default:false
    },
    informeAuditoria:{
        type:Boolean,
        require:true,
        default:false
    },
    planAtencionHallazgos:{
        type:Boolean,
        require:true,
        default:false
    },
    revisionDireccion:{
        type:Boolean,
        require:true,
        default:false
    },
    inspeccionTanques:{
        type:Boolean,
        require:true,
        default:false
    },
    pruebaOperativa:{
        type:Boolean,
        require:true,
        default:false
    },
    inspeccionDispensarios:{
        type:Boolean,
        require:true,
        default:false
    },
    inspeccionAccesorios:{
        type:Boolean,
        require:true,
        default:false
    },
    inspeccionInstalaciones:{
        type:Boolean,
        require:true,
        default:false
    },
    programaLimpieza:{
        type:Boolean,
        require:true,
        default:false
    },
    inspeccionMensual:{
        type:Boolean,
        require:true,
        default:false
    },
    inspeccionSeñalamiento:{
        type:Boolean,
        require:true,
        default:false
    },
    permisoTrabajoPeligroso2:{
        type:Boolean,
        require:true,
        default:false
    
    },
    formatoAcr:{
        type:Boolean,
        require:true,
        default:false
    },
    entrevistaPersonal:{
        type:Boolean,
        require:true,
        default:false
    },
    comprobacionHipotesis:{
        type:Boolean,
        require:true,
        default:false
    
    },
    recomendaccionIcr:{
        type:Boolean,
        require:true,
        default:false
    },
    estadisticaInsidencias:{
        type:Boolean,
        require:true,
        default:false
    },
    //Empieza la requisicion del segundo formulario
    codificacion:{
        type:String,
        require:true
    },
    nombreDocumento:{
        type:String,
        require:true
    },
    elementoSistema:{
        type:String,
        require:true
    
    },
    nombreSolicitante:{
        type:String,
        require:true
    },
    fecha:{
        type:String,
        require:true
    },
    //Empieza serie de Checbox del 2 form
    procedimientoSistema:{
        type:Boolean,
        require:true,
        default:false
    },
    formatoSistema:{
        type:Boolean,
        require:true,
        default:false
    },
    procedimientoEspecifico:{
        type:Boolean,
        require:true,
        default:false
    },
    formatoOperativo:{
        type:Boolean,
        require:true,
        default:false
    },
    origenCambio:{
        type:Boolean,
        require:true,
        default:false
    },
    sugerencia:{
        type:Boolean,
        require:true,
        default:false
    },
    recomendaccionIcr2:{
        type:Boolean,
        require:true,
        default:false
    },
    cambioTecnologia:{
        type:Boolean,
        require:true,
        default:false
    },
    hallazgoAuditoria:{
        type:Boolean,
        require:true,
        default:false
    },
    accionMejora:{
        type:Boolean,
        require:true,
        default:false
    },
    cambioProceso:{
        type:Boolean,
        require:true,
        default:false
    },
    estadoActual:{
        type:Boolean,
        require:true,
        default:false
    },
    cambioPropuesto:{
        type:Boolean,
        require:true,
        default:false
    },
    //Tercer divisor
    aceptada:{
        type:Boolean,
        require:true,
        default:false
    },
    rechazada:{
        type:Boolean,
        require:true,
        default:false
    },
    //Empieza el otro separador
    fechaEntrega:{
    type:String,
    require:true
    },
    nombreDocumento2:{
        type:String,
        require:true
    },
    codigo:{
        type:String,
        require:true
    },
    fechaDocumento:{
        type:String,
        require:true
    },fechaDocumentoSustituye:{
        type:String,
        require:true
    },
    nombrePersonaFirma:{
        type:String,
        require:true
    }
})

module.exports = mongoose.model("Puntoocho",puntoochoSchema);